/**
 * =============================================================================
 * GITHUB ACTIONS GENERATOR — Produces .github/workflows/embedded-ci.yml
 * =============================================================================
 *
 * This generator takes a ProjectProfile and produces a GitHub Actions workflow.
 * It can use either AI-powered generation or template-based fallback.
 */

import { ICiGenerator, GenerationResult } from './types';
import { ProjectProfile } from '../scanner/types';
import { AiOrchestrator } from '../ai/aiOrchestrator';
import { TemplateFallbackGenerator } from '../ai/templateFallback';
import { LlmConfig, PipelineGenerationRequest } from '../ai/types';

export class GitHubActionsGenerator implements ICiGenerator {
  readonly provider = 'github' as const;
  readonly displayName = 'GitHub Actions';

  private aiGenerator: AiOrchestrator | null;
  private templateGenerator: TemplateFallbackGenerator;

  constructor(llmConfig?: LlmConfig, templatesDir?: string) {
    this.templateGenerator = new TemplateFallbackGenerator(templatesDir);

    // Only create the AI generator if we have a valid LLM config
    this.aiGenerator = llmConfig && llmConfig.provider
      ? new AiOrchestrator(llmConfig, templatesDir)
      : null;
  }

  async generate(profile: ProjectProfile, useAi: boolean): Promise<GenerationResult> {
    const request: PipelineGenerationRequest = {
      profile,
      ciProvider: 'github',
    };

    // Choose generator: AI if requested AND available, otherwise template
    const generator = (useAi && this.aiGenerator)
      ? this.aiGenerator
      : this.templateGenerator;

    const response = await generator.generatePipeline(request);

    // Build a human-readable summary
    const envCount = profile.environments.length || 1;
    const summary = [
      `Generated ${this.displayName} workflow for ${profile.projectType} project`,
      `Board: ${profile.board || 'auto-detect'}`,
      `Environments: ${envCount}`,
      `Build system: ${profile.buildSystem}`,
      `Generated by: ${response.usedAi ? 'AI' : 'Template'}`,
    ].join(' | ');

    return {
      yamlContent: response.yaml,
      relativeFilePath: '.github/workflows/embedded-ci.yml',
      provider: 'github',
      generatedBy: response.usedAi ? 'ai' : 'template',
      summary,
    };
  }
}
