/**
 * =============================================================================
 * GITLAB CI GENERATOR — Produces .gitlab-ci.yml
 * =============================================================================
 *
 * Same pattern as GitHub Actions generator but outputs GitLab CI YAML format.
 */

import { ICiGenerator, GenerationResult } from './types';
import { ProjectProfile } from '../scanner/types';
import { AiOrchestrator } from '../ai/aiOrchestrator';
import { TemplateFallbackGenerator } from '../ai/templateFallback';
import { LlmConfig, PipelineGenerationRequest } from '../ai/types';

export class GitLabCiGenerator implements ICiGenerator {
  readonly provider = 'gitlab' as const;
  readonly displayName = 'GitLab CI';

  private aiGenerator: AiOrchestrator | null;
  private templateGenerator: TemplateFallbackGenerator;

  constructor(llmConfig?: LlmConfig, templatesDir?: string) {
    this.templateGenerator = new TemplateFallbackGenerator(templatesDir);
    this.aiGenerator = llmConfig && llmConfig.provider
      ? new AiOrchestrator(llmConfig, templatesDir)
      : null;
  }

  async generate(profile: ProjectProfile, useAi: boolean): Promise<GenerationResult> {
    const request: PipelineGenerationRequest = {
      profile,
      ciProvider: 'gitlab',
    };

    const generator = (useAi && this.aiGenerator)
      ? this.aiGenerator
      : this.templateGenerator;

    const response = await generator.generatePipeline(request);

    const envCount = profile.environments.length || 1;
    const summary = [
      `Generated ${this.displayName} pipeline for ${profile.projectType} project`,
      `Board: ${profile.board || 'auto-detect'}`,
      `Environments: ${envCount}`,
      `Build system: ${profile.buildSystem}`,
      `Generated by: ${response.usedAi ? 'AI' : 'Template'}`,
    ].join(' | ');

    return {
      yamlContent: response.yaml,
      relativeFilePath: '.gitlab-ci.yml',
      provider: 'gitlab',
      generatedBy: response.usedAi ? 'ai' : 'template',
      summary,
    };
  }
}
