/**
 * =============================================================================
 * GENERATOR TYPES — Contracts for CI/CD pipeline generators
 * =============================================================================
 *
 * DESIGN PATTERN: Provider Pattern
 * Just like scanners use the Strategy pattern to handle different project types,
 * generators use the Provider pattern to handle different CI platforms:
 * - GitHub Actions → writes to .github/workflows/
 * - GitLab CI → writes to .gitlab-ci.yml
 * - (Future) Bitbucket Pipelines → writes to bitbucket-pipelines.yml
 *
 * Each provider implements ICiGenerator. The generatorFactory picks the right one.
 */

import { ProjectProfile } from '../scanner/types';

// ---------------------------------------------------------------------------
// CI Provider enum
// ---------------------------------------------------------------------------

/** Supported CI/CD platforms */
export type CiProvider = 'github' | 'gitlab';

// ---------------------------------------------------------------------------
// Generation Result
// ---------------------------------------------------------------------------

/**
 * What the generator produces: the YAML content and where to write it.
 *
 * Why separate content from filePath?
 * - The command handler decides whether to actually write the file
 * - It might want to show a preview first, or ask for confirmation
 * - Keeping them separate follows the Single Responsibility Principle
 */
export interface GenerationResult {
  /** The generated YAML content (ready to write to disk) */
  yamlContent: string;

  /**
   * Relative path where this file should be written, relative to the project root.
   * Examples:
   *   GitHub: '.github/workflows/embedded-ci.yml'
   *   GitLab: '.gitlab-ci.yml'
   */
  relativeFilePath: string;

  /** Which CI provider generated this */
  provider: CiProvider;

  /** Was this generated by AI or by template fallback? */
  generatedBy: 'ai' | 'template';

  /** Human-readable summary of what was generated (for the UI) */
  summary: string;
}

// ---------------------------------------------------------------------------
// Generator Interface
// ---------------------------------------------------------------------------

/**
 * ICiGenerator is the contract every CI provider must implement.
 *
 * ADDING A NEW CI PROVIDER:
 * 1. Create a new class implementing ICiGenerator (e.g., BitbucketPipelinesGen)
 * 2. Register it in generatorFactory.ts
 * 3. Add the provider name to the CiProvider type above
 * 4. That's it — the UI and command handler don't need to change at all
 */
export interface ICiGenerator {
  /** Which CI platform this generator targets */
  readonly provider: CiProvider;

  /** Human-readable name, e.g., 'GitHub Actions' */
  readonly displayName: string;

  /**
   * Generate a CI/CD pipeline YAML from a project profile.
   *
   * @param profile - The detected project characteristics
   * @param useAi - Whether to use AI enhancement (false = pure template mode)
   * @returns The generated YAML and file path info
   */
  generate(profile: ProjectProfile, useAi: boolean): Promise<GenerationResult>;
}

// ---------------------------------------------------------------------------
// Generation Options — user preferences passed through the pipeline
// ---------------------------------------------------------------------------

/**
 * Options that control the generation process.
 * These come from VS Code settings + QuickPick selections.
 */
export interface GenerationOptions {
  /** Which CI platform to generate for */
  ciProvider: CiProvider;

  /** Whether to use AI-enhanced generation */
  useAi: boolean;

  /** LLM provider settings (only relevant if useAi is true) */
  llmConfig?: {
    provider: 'openai' | 'ollama';
    apiKey?: string;
    model?: string;
    baseUrl?: string;
  };
}
